### ISSUE TITLE
Be robust to text edits that happen while fetching a completion

### ISSUE THREAD

**Issue by jameshiew** [jameshiew/nvim-magic#11]
If while a completion is being fetched, the text that was used in the prompt is edited, then the resulting completion can be inserted into the wrong place or result in errors like the below if e.g. the text has changed such that the end mark of the original visual selection is no longer valid anymore:

```
E5108: Error executing lua ...te/pack/packer/start/nvim-magic/lua/nvim-magic/flows.lua:110: end_col out of bounds
```

Extmarks could be used to record where a completion should be appended or inserted over, and would move with the text. Ideally the extmark(s) would highlight until the completion is fetched as well, to give a visual indication.

**Comment by abatilo** [comment]
I seem to get this error even if I'm not editing any text at all. Is there a good way for me to get debug information for me to be able to give you a better bug report?

**Comment by jameshiew** [comment]
@abatilo you can set the envvar `NVIM_MAGIC_LOGLEVEL='debug'` to get debug logs (though they probably aren't super helpful).

**Comment by jameshiew** [comment]
https://github.com/jameshiew/nvim-magic/issues/30 was giving this error if you were using "V" mode (potential fix in `master` now)
