### ISSUE TITLE
Can't see nvim-magic mappings

### ISSUE THREAD

**Issue by shaypal5** [jameshiew/nvim-magic#38]
**Describe the bug**
I can't trigger any of the `nvim-magic` commands, and I can't see any of the mappings `\mcs`, `\mss` or `\mds` when running `:vmap`.

Running `:verbose vmap \mcs` yields "No mapping found".

When I set `use_default_keymap = false` and set manually `xnoremap <Leader>mc <Plug>nvim-magic-append-completion` (I also tried adding parenthesis, as in `xnoremap <Leader>mc <Plug>(nvim-magic-append-completion)`) I could see the mapping, but it had an `x` next to it.

As far as I can tell Iv'e set up nvim-magic correctly, including the right environment variable with my OpenAI key, and all requirements are installed correctly.

**To Reproduce**
Run `:vmap \mcs`

**Expected behavior**
Magic append completion to work.

**Details (please complete the following information):**
 - OS: macOS BigSure 11.6.1
 - Neovim version: `v0.6.1`
 - nvim-magic version: [e.g. v0.3.1, commit 6c04695c2f4a6d15dbb3d370328865878e6fbc29]

My config (inside packer.nvim setup):
```lua
	use({
		'jameshiew/nvim-magic',
		config = function()
			require('nvim-magic').setup({
				-- default backends setup; probably shouldnt touch this
				backends = {
					default = require('nvim-magic-openai').new(),
				},
				-- I set this to false to set my own mapping
				use_default_keymap = false,
            })
		end,
		requires = {
			'nvim-lua/plenary.nvim',
			'MunifTanjim/nui.nvim'
		}
	})
```

**Comment by jameshiew** [comment]
Thanks for the detailed report, I'm not sure what could be causing this. As a workaround, are you able to run the Lua commands directly?
e.g. highlight some text in Visual mode then run `:'<,'>lua require('nvim-magic.flows').append_completion(require('nvim-magic').backends.default)` as an alternative to pressing `\mcs` or mapping something to `<Plug>nvim-magic-append-completion` (the other Lua commands being mapped to are in [lua/nvim-magic/_keymaps.lua](https://github.com/jameshiew/nvim-magic/blob/0.3.1/lua/nvim-magic/_keymaps.lua)). You can also turn on debug logging with the envvar `export NVIM_MAGIC_LOGLEVEL='debug'` which might provide some more info.

**Comment by shaypal5** [comment]
Thank you for the plugin!

I'm closing this for now as I've moved to using GitHub Copilot so I can't put time into walking through debugging this. Sorry. <3
