### ISSUE TITLE
Max tokens used when fetching completions should be explicitly configurable

### ISSUE THREAD

**Issue by jameshiew** [jameshiew/nvim-magic#4]
Currently they default to `300` for code completion flow and `1000` for suggestions/docstring flows but they should be easily overrideable as OpenAI charges per token generated.

**Comment by martasd** [comment]
Hi @jameshiew Why did you decide not to add this option?

**Comment by jameshiew** [comment]
I won't be maintaining this repo anymore (will archive it soon), I guess this feature could still be useful if someone decides to fork this project
